### **Problem 2. Matrix Operations**

In [3]:
import numpy as np
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
A = rng.random((100 ,100))
B = rng.random((100 ,200))
C = rng.random((100 ,200))
D = rng.random((100 ,100))
u = rng.random((100 ,1))
v = rng.random((200 ,1))

**2.1 (0.5/5) Matrix Norms**

In [4]:
###### YOUR CODE STARTS HERE ######
solution_1_a = np.linalg.norm(A)

solution_1_b = np.linalg.norm(B-C)

################Nintendo###################
print(solution_1_a)
print()
print(solution_1_b)

57.74200003983731

57.70681874358965



**2.2 (0.5/5) Matrix Indexing**

In [5]:
###### YOUR CODE STARTS HERE ######

solution_2_a = A[:51,:51]

solution_2_b = B[-30:,-25:]

###################################
print(solution_2_a)
print()
print(solution_2_b)

[[0.79333519 0.53234793 0.96829602 ... 0.78390693 0.68519395 0.04437755]
 [0.1763813  0.52431572 0.4796792  ... 0.17326307 0.32912718 0.36806651]
 [0.30262439 0.67864651 0.9236463  ... 0.10286055 0.39408668 0.74327311]
 ...
 [0.71609013 0.56005288 0.21113662 ... 0.81960495 0.22536406 0.56719967]
 [0.92617281 0.58412361 0.09277974 ... 0.41390725 0.40219501 0.16960008]
 [0.81069591 0.05835176 0.17480185 ... 0.98657952 0.78458467 0.40632044]]

[[0.05021279 0.69170802 0.88003647 0.86432376 0.1581059  0.60586831
  0.93232267 0.93305442 0.98757247 0.83542562 0.21714824 0.43499939
  0.48844572 0.00903565 0.06751099 0.60276914 0.86607322 0.53085673
  0.71437729 0.30859202 0.50501977 0.9842853  0.71678392 0.19249453
  0.2042969 ]
 [0.7436891  0.156883   0.3041397  0.68713496 0.91658955 0.93108287
  0.5383418  0.31713155 0.20115251 0.98290047 0.42729396 0.646887
  0.67630424 0.99037675 0.67131465 0.82544824 0.04484094 0.41576832
  0.73421817 0.17796458 0.05871652 0.63116432 0.07212953 0.88846977

**2.3 (0.5/5) Matrix Vector Multiplication**

In [6]:
###### YOUR CODE STARTS HERE ######

solution_3_a = A @ u

solution_3_b = C.T @ u

solution_3_c = B @ v

###################################
print(solution_3_a)
print()
print(solution_3_b)
print()
print(solution_3_c)

[[28.50366073]
 [25.02450298]
 [23.49907462]
 [25.27969675]
 [24.47178266]
 [22.33796921]
 [26.57345786]
 [25.01678311]
 [25.31124626]
 [23.7828842 ]
 [27.08123818]
 [28.87822185]
 [25.97580612]
 [28.53006221]
 [23.22761141]
 [27.27799294]
 [29.50883798]
 [26.11828969]
 [27.86338118]
 [26.3818975 ]
 [26.06150034]
 [28.66244049]
 [23.97092477]
 [26.45884712]
 [29.75472154]
 [27.82610464]
 [24.19483163]
 [23.9078858 ]
 [24.9327684 ]
 [27.82415087]
 [24.66101177]
 [23.44902365]
 [25.75882103]
 [25.2778425 ]
 [25.56194592]
 [21.40330819]
 [30.62366736]
 [24.03757644]
 [25.52806573]
 [26.67983794]
 [22.87755865]
 [25.44250295]
 [26.95399897]
 [26.90344647]
 [24.78447057]
 [26.98582772]
 [23.4855198 ]
 [26.88964765]
 [26.29547926]
 [27.95028366]
 [26.22671379]
 [24.55487272]
 [26.03966206]
 [26.01756539]
 [24.94436589]
 [28.22844437]
 [26.94397522]
 [25.3802767 ]
 [27.49657148]
 [25.07883323]
 [23.97605905]
 [27.09484738]
 [26.60851525]
 [27.03974164]
 [25.99494529]
 [28.59206307]
 [28.98704

**2.4 (0.5/5) Matrix Matrix Multiplication**

In [7]:
###### YOUR CODE STARTS HERE ######

solution_4_a = A @ B

solution_4_b = B @ C.T

solution_4_c = C.T @ B

solution_4_d = u @ v.T

###################################
print(solution_4_a)
print()
print(solution_4_b)
print()
print(solution_4_c)
print()
print(solution_4_d)

[[30.8553318  26.85849991 25.51627766 ... 29.20349246 27.3055701
  26.74263608]
 [24.26443946 21.43092486 21.5302041  ... 24.20399327 23.28599256
  23.97975368]
 [24.90081949 22.06556189 20.22395588 ... 24.19942661 23.66107708
  22.51155574]
 ...
 [27.31938486 23.49972061 23.51936217 ... 25.35395168 24.7634286
  25.56955706]
 [23.96545233 21.39459129 21.03569249 ... 23.7148634  22.4765308
  22.45822608]
 [26.31525144 24.19178642 23.93956876 ... 26.55972137 24.538407
  25.79819622]]

[[52.02286646 50.19050542 47.81653568 ... 47.08085411 49.6887287
  45.78161476]
 [54.69976131 50.59818643 51.06852903 ... 45.94864595 51.75891178
  49.52285666]
 [55.65743212 52.445927   53.95243919 ... 47.41993152 53.741838
  50.78497365]
 ...
 [52.64418104 50.00298611 50.18743858 ... 45.15876239 49.78542083
  48.25158544]
 [58.76476206 54.39009003 55.71687647 ... 50.76729243 56.11877232
  55.93370283]
 [50.89210939 47.00805355 48.03910183 ... 43.96947987 51.77024936
  48.61557567]]

[[24.81255476 21.39396

**2.5 (1.5/5) Matrix Power**

Implement your own function first:

In [8]:
# Problem 2.5 (a)
def mat_pow(A,p):
  # check input
  assert A.shape[0] == A.shape[1], "Matrix input needs to be square!"
  assert p > 0, "p should be a positive integer!"
  assert isinstance(p, int), "p should have the data type of integer!"

  ###### YOUR CODE STARTS HERE ######
  Ap = A
  for i in range(p-1):
    Ap = Ap @ A
  #    ....
  ###################################
  return Ap

# print (mat_pow(A, 2))
# np.linalg.matrix_power(A, 2)

Call your own function to solve the given questions:

In [9]:
from numpy.matrixlib.defmatrix import mat
print("Problem 2.5(b)")
###### YOUR CODE STARTS HERE ######

solution_5_b_1 = mat_pow(A,6) @ mat_pow(A, 8) # put (A^6)(A^8)here

solution_5_b_2 = mat_pow(A, 6+8) # put A^(6+8) here

relative_dist_5_b = np.linalg.norm(solution_5_b_1 - solution_5_b_2) / (np.linalg.norm(solution_5_b_1))

###################################
print(solution_5_b_1)
print()
print(solution_5_b_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_5_b)

Problem 2.5(b)
[[6.82121164e+21 6.75401019e+21 6.56120472e+21 ... 6.94310392e+21
  7.09159168e+21 7.16716485e+21]
 [5.72956559e+21 5.67311885e+21 5.51116938e+21 ... 5.83195059e+21
  5.95667482e+21 6.02015349e+21]
 [5.67054215e+21 5.61467690e+21 5.45439576e+21 ... 5.77187243e+21
  5.89531180e+21 5.95813654e+21]
 ...
 [6.05598165e+21 5.99631912e+21 5.82514331e+21 ... 6.16419958e+21
  6.29602940e+21 6.36312448e+21]
 [5.42889030e+21 5.37540577e+21 5.22195506e+21 ... 5.52590237e+21
  5.64408133e+21 5.70422878e+21]
 [6.06462585e+21 6.00487816e+21 5.83345802e+21 ... 6.17299825e+21
  6.30501625e+21 6.37220710e+21]]

[[6.82121164e+21 6.75401019e+21 6.56120472e+21 ... 6.94310392e+21
  7.09159168e+21 7.16716485e+21]
 [5.72956559e+21 5.67311885e+21 5.51116938e+21 ... 5.83195059e+21
  5.95667482e+21 6.02015349e+21]
 [5.67054215e+21 5.61467690e+21 5.45439576e+21 ... 5.77187243e+21
  5.89531180e+21 5.95813654e+21]
 ...
 [6.05598165e+21 5.99631912e+21 5.82514331e+21 ... 6.16419958e+21
  6.29602940e+21

In [10]:
print("Problem 2.5(c)")
###### YOUR CODE STARTS HERE ######

solution_5_c_1 = mat_pow(mat_pow(A,6), 8) # put (A^6)^8 here

solution_5_c_2 = mat_pow(A, 6*8) # put A^(6*8) here

relative_dist_5_c = (np.linalg.norm(solution_5_c_1 - solution_5_c_2))/np.linalg.norm(solution_5_c_1)

###################################
print(solution_5_c_1)
print()
print(solution_5_c_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_5_c)
print()

Problem 2.5(c)
[[4.06604983e+79 4.02599178e+79 3.91106254e+79 ... 4.13870849e+79
  4.22722042e+79 4.27226876e+79]
 [3.41533153e+79 3.38168424e+79 3.28514793e+79 ... 3.47636211e+79
  3.55070886e+79 3.58854780e+79]
 [3.38014830e+79 3.34684763e+79 3.25130580e+79 ... 3.44055017e+79
  3.51413104e+79 3.55158018e+79]
 ...
 [3.60990458e+79 3.57434040e+79 3.47230436e+79 ... 3.67441211e+79
  3.75299443e+79 3.79298907e+79]
 [3.23610227e+79 3.20422073e+79 3.11275043e+79 ... 3.29393010e+79
  3.36437530e+79 3.40022853e+79]
 [3.61505730e+79 3.57944235e+79 3.47726067e+79 ... 3.67965690e+79
  3.75835139e+79 3.79840312e+79]]

[[4.06604983e+79 4.02599178e+79 3.91106254e+79 ... 4.13870849e+79
  4.22722042e+79 4.27226876e+79]
 [3.41533153e+79 3.38168424e+79 3.28514793e+79 ... 3.47636211e+79
  3.55070886e+79 3.58854780e+79]
 [3.38014830e+79 3.34684763e+79 3.25130580e+79 ... 3.44055017e+79
  3.51413104e+79 3.55158018e+79]
 ...
 [3.60990458e+79 3.57434040e+79 3.47230436e+79 ... 3.67441211e+79
  3.75299443e+79

**2.6 (1.5/5) Inverse and Transpose**

In [11]:
print("Problem 2.6(a)")
###### YOUR CODE STARTS HERE ######

solution_6_a_1 = np.linalg.inv(A @ D) # put (AD)^(-1) here

solution_6_a_2 = np.linalg.inv(D) @ np.linalg.inv(A) # put (D^(-1))(A^(-1)) here

relative_dist_6_a = np.linalg.norm(solution_6_a_1 - solution_6_a_1) / np.linalg.norm(solution_6_a_1)

###################################
print(solution_6_a_1)
print()
print(solution_6_a_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_a)
print()

Problem 2.6(a)
[[ 0.70241716 -0.11887631 -0.01860073 ...  0.3831288  -1.84655533
   0.79094459]
 [-1.13752384  0.65959528  1.14422686 ... -0.18080572  2.39156577
  -2.5844308 ]
 [ 2.35081072  2.38360334  0.37764606 ... -5.83321087 -4.42518068
   0.88195665]
 ...
 [ 1.04698234  0.03666391 -0.20132336 ... -0.7108995  -1.90437116
   0.8166152 ]
 [-0.49719463  1.87804098  1.08613673 ... -3.04486687  1.25604577
  -1.91659232]
 [ 0.47327828  1.80665959  0.87778447 ... -3.65748743 -0.59594225
  -0.84389141]]

[[ 0.70241716 -0.11887631 -0.01860073 ...  0.3831288  -1.84655533
   0.79094459]
 [-1.13752384  0.65959528  1.14422686 ... -0.18080572  2.39156577
  -2.5844308 ]
 [ 2.35081072  2.38360334  0.37764606 ... -5.83321087 -4.42518068
   0.88195665]
 ...
 [ 1.04698234  0.03666391 -0.20132336 ... -0.7108995  -1.90437116
   0.8166152 ]
 [-0.49719463  1.87804098  1.08613673 ... -3.04486687  1.25604577
  -1.91659232]
 [ 0.47327828  1.80665959  0.87778447 ... -3.65748743 -0.59594225
  -0.84389141]]


In [12]:
print("Problem 2.6(b)")
###### YOUR CODE STARTS HERE ######
solution_6_b_1 = (np.linalg.inv(A)).T # put (A^(-1))^T here

solution_6_b_2 = np.linalg.inv(A.T) # put (A^T)^(-1) here

relative_dist_6_b = np.linalg.norm(solution_6_b_1 - solution_6_b_1) / np.linalg.norm(solution_6_b_1)

###################################
print(solution_6_b_1)
print()
print(solution_6_b_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_b)
print()

Problem 2.6(b)
[[-0.14244373  0.31938734  0.4253962  ...  0.52705441  0.56788036
  -0.24916076]
 [ 0.29078049  0.13530854  0.09055331 ... -0.22288197  0.44456525
  -0.16393567]
 [ 0.28617452  0.01831374 -0.15338794 ... -0.20293826  0.16533199
  -0.32448681]
 ...
 [-0.70332541  0.00336139 -0.3593826  ... -0.15153609 -1.30186675
  -0.05689874]
 [ 0.45571424 -0.53804559 -0.66695996 ... -0.69917034 -1.02549203
   0.33044975]
 [-0.63647771  0.41013419  0.56754231 ...  0.44011542  0.0570875
   0.07178524]]

[[-0.14244373  0.31938734  0.4253962  ...  0.52705441  0.56788036
  -0.24916076]
 [ 0.29078049  0.13530854  0.09055331 ... -0.22288197  0.44456525
  -0.16393567]
 [ 0.28617452  0.01831374 -0.15338794 ... -0.20293826  0.16533199
  -0.32448681]
 ...
 [-0.70332541  0.00336139 -0.3593826  ... -0.15153609 -1.30186675
  -0.05689874]
 [ 0.45571424 -0.53804559 -0.66695996 ... -0.69917034 -1.02549203
   0.33044975]
 [-0.63647771  0.41013419  0.56754231 ...  0.44011542  0.0570875
   0.07178524]]

r

In [13]:
print("Problem 2.6(c)")
###### YOUR CODE STARTS HERE ######

solution_6_c_1 = (A@B).T # put (AB)^(T) here (Updated)

solution_6_c_2 = B.T @ A.T # put (B^T)(A^T) here

relative_dist_6_c = np.linalg.norm(solution_6_c_1 - solution_6_c_1) / np.linalg.norm(solution_6_c_1)

###################################
print(solution_6_c_1)
print()
print(solution_6_c_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_c)

Problem 2.6(c)
[[30.8553318  24.26443946 24.90081949 ... 27.31938486 23.96545233
  26.31525144]
 [26.85849991 21.43092486 22.06556189 ... 23.49972061 21.39459129
  24.19178642]
 [25.51627766 21.5302041  20.22395588 ... 23.51936217 21.03569249
  23.93956876]
 ...
 [29.20349246 24.20399327 24.19942661 ... 25.35395168 23.7148634
  26.55972137]
 [27.3055701  23.28599256 23.66107708 ... 24.7634286  22.4765308
  24.538407  ]
 [26.74263608 23.97975368 22.51155574 ... 25.56955706 22.45822608
  25.79819622]]

[[30.8553318  24.26443946 24.90081949 ... 27.31938486 23.96545233
  26.31525144]
 [26.85849991 21.43092486 22.06556189 ... 23.49972061 21.39459129
  24.19178642]
 [25.51627766 21.5302041  20.22395588 ... 23.51936217 21.03569249
  23.93956876]
 ...
 [29.20349246 24.20399327 24.19942661 ... 25.35395168 23.7148634
  26.55972137]
 [27.3055701  23.28599256 23.66107708 ... 24.7634286  22.4765308
  24.538407  ]
 [26.74263608 23.97975368 22.51155574 ... 25.56955706 22.45822608
  25.79819622]]

rel