### **Problem 3. Gaussian Elimination and Back Substitution**


Import required packages, and create matrix A and vector b

In [59]:
import numpy as np
from numpy.linalg import norm
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
n = 300
A = rng.random((n,n))
b = rng.random((n,1))
#print("A = {}; \n b = {}".format(A,b))

**3.1 (1.5/5) Gaussian Elimination (Version 0)**



**Implement your own function: TODO**

In [51]:
def gauss_elim_v0(A,b,print_flag=True):
  # check whether the calculation is valid
  assert A.shape[0] == A.shape[1],"A must be square!" # Make sure A is square
  assert A.shape[0] == b.shape[0],"Input dimension doesn't match!" # Make sure dimmension matches
  assert b.shape[1] == 1,"b is not a vector!" # Make sure b is a vector


    # Perform Gaussian elimination
  U = np.hstack((A, b))
  n = A.shape[0]
  for k in range(0,n-1):
    for j in range(k + 1, n):
      lamb = U[j, k] / U[k, k]
      U[[j],:] = U[[j],:] - lamb * U[[k],:]
  ###################################
  return U

**Validate your result here using the example shown to you**

In [52]:
A_example1 = np.array([[1,-1,1],[2,-1,3],[2,0,3]],dtype=np.float64)
b_example1 = np.array([[1],[4],[5]],dtype=np.float64)

U_example1 = gauss_elim_v0(A_example1,b_example1,True)

print(U_example1)

[[ 1. -1.  1.  1.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -1. -1.]]


**3.2 (2/5) Back Substitution**

In [53]:
# this function will check whether the matrix is in row echelon form
def check_row_echelon(U):
  eps = np.finfo(np.float32).eps # updated here!!!
  # Previous version: eps = np.finfo(np.float64).eps
  test = np.tril(U,-1)
  #print(test) np.abs(test)
  return np.all(abs(test)<=eps)


**Implement your own function: TODO**

In [54]:
def back_subs(U,print_flag = True):
  assert  check_row_echelon(U),"U must be in row echelon form"

  ###### YOUR CODE STARTS HERE ######
  n = U.shape[0]
  x = np.zeros((n,1))
  c = U[:, [-1]]
  D = U[:,:-1]
  x[n-1] = c[n-1]/D[n-1, n-1]
  for i in range(n-2, -1, -1):
    sum = np.sum(D[i,i+1:] * x[i+1:])
    x[i] = (c[i] - sum)/D[i,i]
    if(print_flag):
      print(f'x[{i}] = {x[i]}')
  return x

Validate your result here using the example shown to you

In [55]:
x_example1 = back_subs(U_example1,True)
print(x_example1)

x[1] = [1.]
x[0] = [1.]
[[1.]
 [1.]
 [1.]]


**Call your own functions and validate your solutions (x1) by using relative distance ||Ax1 - b||/||A||: TODO**

In [56]:
def my_solver_v0(A,b):
  U = gauss_elim_v0(A,b,False)
  ###### YOUR CODE STARTS HERE ######
  x = back_subs(U, False)

  return x

Validate your result here

In [65]:
###### YOUR CODE STARTS HERE ######
x1 = my_solver_v0(A_example1 ,b_example1 )
dist = np.linalg.norm(A_example1 @ x1 - b_example1 ) / np.linalg.norm(A_example1 )

print("The relative error ||Ax1-b||/||A|| = {}".format(dist))

The relative error ||Ax1-b||/||A|| = 0.0


**Call the numpy built-in function to solve the given questions (solution is x2), and compare it with your result using relative distance ||x1-x2||/||x2||: TODO**

In [67]:
###### YOUR CODE STARTS HERE ######

x2 = np.linalg.solve(A_example1 ,b_example1 )

dist = np.linalg.norm(x1 - x2) / np.linalg.norm(x2)

###################################
print("The relative distance ||A@x2-b||/||A|| = {}".format(dist))

The relative distance ||A@x2-b||/||A|| = 0.0


**3.3 (1.5/5) Gaussian Elimination (Version 1)**

In [ ]:
A[0,0] = 0

**Implement your own function: TODO**

In [68]:
def gauss_elim_v1(A,b,print_flag):
  # check whether the calculation is valid
  assert A.shape[0] == A.shape[1],"A must be square" # Make sure A is square
  assert A.shape[0] == b.shape[0],"Input dimension doesn't match" # Make sure dimmension matches
  assert b.shape[1] == 1,"b is not a vector" # Make sure b is a vector

  n = A.shape[0]
  ###### YOUR CODE STARTS HERE ######
  U = np.concatenate((A,b), axis = 1)
  for k in range (0, n-1):
    max_row = np.argmax(np.abs(U[k:, k])) + k
    U[[k, max_row], :] = U[[max_row, k], :]
    for j in range (k+1, n):
      lamb = U[j,k]/U[k,k]
      U[[j], :] -= lamb * U[[k], :]
    #   print your augmented matrix each step while it is modified
  #   you could symply use print(U) to print for each step
      if (print_flag):
        print(U)
        print("==============================================")
  ###################################
  return U

In [72]:
def my_solver_v1(A,b):
  U = gauss_elim_v1(A,b,False)
  ###### YOUR CODE STARTS HERE ######
  x = back_subs(U,False) # reuse your back_substitution function here
  ###################################

  return x

**Validate your result here using the example shown to you**

In [73]:
A_example2 = np.array([[0,1,1],[2,6,4],[1,1,4]],dtype=np.float64)
b_example2 = np.array([[-1],[6],[9]],dtype=np.float64)

U_example2 = gauss_elim_v1(A_example2,b_example2,True)

print(U_example2)

[[ 2.  6.  4.  6.]
 [ 0.  1.  1. -1.]
 [ 1.  1.  4.  9.]]
[[ 2.  6.  4.  6.]
 [ 0.  1.  1. -1.]
 [ 0. -2.  2.  6.]]
[[ 2.  6.  4.  6.]
 [ 0. -2.  2.  6.]
 [ 0.  0.  2.  2.]]
[[ 2.  6.  4.  6.]
 [ 0. -2.  2.  6.]
 [ 0.  0.  2.  2.]]


**Call your own functions and validate your solutions (x1) by using relative distance ||Ax1 - b||/||A||: TODO**

In [76]:
###### YOUR CODE STARTS HERE ######

x1 = my_solver_v1(A,b)
dist = np.linalg.norm(A @ x1 - b)/np.linalg.norm(A)


###################################
print("The relative error ||Ax1-b||/||A|| = {}".format(dist))

The relative error ||Ax1-b||/||A|| = inf


**Call the numpy built-in function to solve the given questions (solution is x2), and compare it with your result using relative distance ||x1-x2||/||x2||: TODO**

In [ ]:
###### YOUR CODE STARTS HERE ######

# x2 = np.??
# dist = ...
#

###################################
print("The relative distance ||x1-x2||/||x2|| = {}".format(dist))