### **Problem 1. Vector Operations**

In [1]:
import numpy as np
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
u = rng.random((10000 ,1))
v = rng.random((10000 ,1))
w = rng.random((10000 ,1))

**1.1 (1.5/5) Vector Indexing and Concatenation**

In [6]:
###### YOUR CODE STARTS HERE ######

solution_1_a = u[2022]

solution_1_b = v[2022:2033]

solution_1_c = np.concatenate([u[:30], w[-100:]])

###################################
print(solution_1_a)
print()
print(solution_1_b)
print()
print(solution_1_c)

[0.60314211]

[[0.65678602]
 [0.62798177]
 [0.738143  ]
 [0.94811149]
 [0.55179546]
 [0.64332468]
 [0.13413764]
 [0.88390343]
 [0.81123801]
 [0.652259  ]
 [0.79811821]]

[[0.79333519]
 [0.53234793]
 [0.96829602]
 [0.63381521]
 [0.23578471]
 [0.52733685]
 [0.42189232]
 [0.41183741]
 [0.66958871]
 [0.15178221]
 [0.87100325]
 [0.81715053]
 [0.67466176]
 [0.80733747]
 [0.35508676]
 [0.08664731]
 [0.36742027]
 [0.57970373]
 [0.05025996]
 [0.72685397]
 [0.58131197]
 [0.47721682]
 [0.1436494 ]
 [0.58801681]
 [0.46627275]
 [0.05475264]
 [0.14921417]
 [0.93784232]
 [0.81463425]
 [0.72207311]
 [0.85395778]
 [0.35686649]
 [0.82820314]
 [0.84829925]
 [0.41450186]
 [0.80222036]
 [0.291635  ]
 [0.96926886]
 [0.13700848]
 [0.47577132]
 [0.28188049]
 [0.37626924]
 [0.92659446]
 [0.76645543]
 [0.06965738]
 [0.16633979]
 [0.86241119]
 [0.61268771]
 [0.42784691]
 [0.52975043]
 [0.50287865]
 [0.78688485]
 [0.42783973]
 [0.85291338]
 [0.2349399 ]
 [0.51221287]
 [0.67892029]
 [0.84400258]
 [0.62394493]
 [0.

**1.2 (1/5) Linear Combination**

In [7]:
###### YOUR CODE STARTS HERE ######
solution_2_a = u + v + w
solution_2_b = 2*u + 3*v + 3*w

###################################
print(solution_2_a)
print()
print(solution_2_b)

[[2.08485402]
 [1.73665664]
 [1.50197551]
 ...
 [2.29001003]
 [1.9876794 ]
 [1.64777379]]

[[5.46122687]
 [4.67762199]
 [3.5376305 ]
 ...
 [6.3975946 ]
 [5.16694204]
 [4.42177553]]


**1.3 (1.5/5) Inner Product**

In [8]:
###### YOUR CODE STARTS HERE ######

solution_3_a = np.inner(u,u)

solution_3_b = np.inner(u-2*v, w)

solution_3_c = np.inner(3*u, 2*v + w)
###################################
print(solution_3_a)
print()
print(solution_3_b)
print()
print(solution_3_c)

[[0.62938073 0.42233035 0.76818331 ... 0.37479969 0.63157109 0.41376068]
 [0.42233035 0.28339432 0.51547039 ... 0.25150005 0.42380014 0.27764386]
 [0.76818331 0.51547039 0.93759719 ... 0.4574574  0.77085674 0.50501078]
 ...
 [0.37479969 0.25150005 0.4574574  ... 0.22319528 0.37610407 0.24639677]
 [0.63157109 0.42380014 0.77085674 ... 0.37610407 0.63376909 0.41520065]
 [0.41376068 0.27764386 0.50501078 ... 0.24639677 0.41520065 0.27201008]]

[[-0.40004348 -0.55881496 -0.10995208 ... -0.79819382 -0.54586569
  -0.12386006]
 [-0.27165445 -0.37947018 -0.07466431 ... -0.54202334 -0.37067682
  -0.0841087 ]
 [ 0.07090431  0.09904521  0.01948807 ...  0.14147308  0.09675006
   0.02195315]
 ...
 [-0.61025463 -0.85245589 -0.16772868 ... -1.21762135 -0.83270215
  -0.18894491]
 [-0.1522333  -0.21265251 -0.04184137 ... -0.30374619 -0.20772476
  -0.04713394]
 [-0.66563577 -0.929817   -0.18295021 ... -1.32812154 -0.90827059
  -0.20609182]]

[[5.05192537 4.20192931 2.23916167 ... 6.46542311 4.17682401 5

**1.4 (1/5) Vector Norm**

In [9]:
###### YOUR CODE STARTS HERE ######

solution_4_a = np.linalg.norm(u)

solution_4_b = np.linalg.norm(v + 3*w)
###################################
print(solution_4_a)
print()
print(solution_4_b)

57.74200003983731

219.0097026340124
